name: Upload PyTest cache

description: Uploads the pytest cache to S3

inputs:
  cache_dir:
    description: Unique identifier that only repeats when the same workflow is being run against the same PR
    required: true
  pr-identifier:
    description: Unique identifier that only repeats when the same workflow is being run against the same PR
    required: true
  shard:
    description: Shard number for the current job
    required: false
    default: "0"

outputs:
  pr-identifier:
    description: "Processed identifier"
    value: ${{ steps.get-id.pr-identifier }}

runs:
  using: composite
  steps:
    - name: Get the S3 key
      id: get-id
      shell: bash
      env:
        CACHE_DIR: ${{ inputs.cache_dir }}
        PR_IDENTIFIER: ${{ inputs.pr-identifier }}
        WORKFLOW: ${{ github.workflow }}
        JOB: ${{ github.job }}
        SHARD: ${{ inputs.shard }}
      run: |
        python3 .github/scripts/pytest_cache.py \
          --upload \
          --cache_dir $CACHE_DIR \
          --pr_identifier $PR_IDENTIFIER \
          --workflow $WORKFLOW \
          --job $JOB \
          --shard $SHARD \
          --temp_dir $RUNNER_TEMP \