name: Upload PyTest cache

description: Uploads the pytest cache to S3

inputs:
  cache_dir:
    description: Path to the pytest cache directory, relative to $GITHUB_WORKSPACE. This folder will be zipped and uploaded to S3.
    required: true
  shard:
    description: Shard number for the current job
    required: false
    default: "0"

runs:
  using: composite
  steps:
    - name: Upload the cache
      shell: bash
      env:
        CACHE_DIR: ${{ inputs.cache_dir }}
        WORKFLOW: ${{ github.workflow }}
        JOB: ${{ github.job }}
        SHARD: ${{ inputs.shard }}
      run: |
        pip3 install boto3
        python3 .github/scripts/pytest_cache.py \
          --upload \
          --cache_dir $CACHE_DIR \
          --pr_identifier $GITHUB_REF \
          --workflow $WORKFLOW \
          --job $JOB \
          --shard $SHARD \
          --temp_dir $RUNNER_TEMP \