name: Upload PyTest cache

description: Uploads the pytest cache to S3

inputs:
  cache_dir:
    description: Path to the pytest cache directory. This is where the merged cache will be placed.
    required: true

outputs:
  pr-identifier:
    description: "Processed identifier"
    value: ${{ steps.get-id.pr-identifier }}

runs:
  using: composite
  steps:
    - name: Get the S3 key
      id: get-id
      shell: bash
      env:
        CACHE_DIR: ${{ inputs.cache_dir }}
        WORKFLOW: ${{ github.workflow }}
        JOB: ${{ github.job }}
        SHARD: ${{ inputs.shard }}
      run: |
        pip3 install boto3
        set +x

        echo "all the commands sent to the below script:""
        echo "cache_dir: $CACHE_DIR"
        echo "pr_identifier: $GITHUB_REF"
        echo "workflow: $WORKFLOW"
        echo "job: $JOB"
        echo "shard: $SHARD"
        echo "temp_dir: $RUNNER_TEMP"


        python3 .github/scripts/pytest_cache.py \
          --upload \
          --cache_dir $CACHE_DIR \
          --pr_identifier $GITHUB_REF \
          --workflow $WORKFLOW \
          --job $JOB \
          --shard $SHARD \
          --temp_dir $RUNNER_TEMP \